"""Add intelligent agent tables

Revision ID: 64ab723f283e
Revises: 763c31703550
Create Date: 2025-06-12 10:55:38.797091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ab723f283e'
down_revision: Union[str, None] = '763c31703550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_profiles_new_id'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_new_user_id'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_new_voice_id'), table_name='voice_profiles')
    op.create_index(op.f('ix_voice_profiles_id'), 'voice_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_voice_profiles_user_id'), 'voice_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_profiles_voice_id'), 'voice_profiles', ['voice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_profiles_voice_id'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_user_id'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_id'), table_name='voice_profiles')
    op.create_index(op.f('ix_voice_profiles_new_voice_id'), 'voice_profiles', ['voice_id'], unique=1)
    op.create_index(op.f('ix_voice_profiles_new_user_id'), 'voice_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_profiles_new_id'), 'voice_profiles', ['id'], unique=False)
    # ### end Alembic commands ###
