"""Add voice settings to podcasts

Revision ID: 9b1e7434b103
Revises: 7c2d99328754
Create Date: 2025-06-08 08:19:13.109957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1e7434b103'
down_revision: Union[str, None] = '7c2d99328754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('voice_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'voice_settings')
    # ### end Alembic commands ###
